config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'api'

urlpatterns = [
    path('', views.companies_view),
]

main/models.py
from django.db import models

class Company(models.Model):
    name = models.CharField(max_length=100)

class Employee(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    comment = models.TextField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

main/forms.py
from django import forms
from main.models import Employee

class EmployeeForm(forms.Form):
    employee = forms.ModelChoiceField(queryset=Employee.objects.all())

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from main.models import Company, Employee
from main.forms import EmployeeForm

def companies_view(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            employee_id = form.cleaned_data['employee']
            company_id = request.POST['company_id']
            company = Company.objects.get(pk=company_id)
            employee = Employee.objects.get(pk=employee_id)
            employee.company = company
            employee.save()
            return redirect('companies_view')
    else:
        companies = Company.objects.all()
        employee_form = EmployeeForm()
        return render(request, 'companies.html', {'companies': companies, 'employee_form': employee_form})

templates/companies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Companies List</title>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 70%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>
<body>
<table>
    <tr>
        <th style="width: 20%;">Company</th>
        <th>Employees</th>
    </tr>
    {% for company in companies %}
    <tr>
        <td>{{ company.name }} <a href="{% url 'add_employee' company.id %}">(Add Employee)</a></td>
        <td>
            {% for employee in company.employee_set.all %}
                {{ employee.first_name }} {{ employee.last_name }},
            {% endfor %}
        </td>
    </tr>
    {% endfor %}
</table>

<div>
    <h3>Add Employee to Company</h3>
    <form method="post">